apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: httpbin-uat
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: uat
  secretRef:
    name: flux-system
  url: ssh://git@github.com/christianackman/fleet-infra
