name: Release Helm Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Modified Chart
        run: |
          chart=$(echo "${{ github.event.head_commit.message }}" | awk '{print $2}')
          echo $chart
          echo "CHART_NAME=$chart" >> $GITHUB_ENV

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # https://github.com/helm/chart-releaser/pull/111
          ## Specifying a single chart to avoid releasing all charts which may already be released
          ## This could be removed once implemented in the action
        with:
          charts_dir: "charts/${{ env.CHART_NAME }}"
          charts_repo_url: "http://christianackman.com/charts/"
